### ISSUE TITLE
Qt not found when cmake.buildDirectory uses variables

### ISSUE THREAD

**Issue by zrno** [tonka3000/vscode-qt-tools#17]
The extension can not find Qt in our case because the cmake.buildDirectory uses variables. In our example the buildDirectory is `${workspaceFolder}/../CMakeBuild/vscode/${buildKit}/${buildType}`

The error message reported:
`ENOENT: no such file or directory, watch 'c:\Projects\XXX/../CMakeBuild/vscode/${buildKit}/${buildType}'`

**Comment by tonka3000** [comment]
Hey,

that's a tricky problem. Are `${buildKit}` and `${buildType}` from the cmake tools itself?

**Comment by zrno** [comment]
Yes. You can choose the build kit in the bottom status bar. Some examples are Clang, Visual Studio, Gcc... buildType is most often Debug, Release, ReleaseDbgInfo...

**Comment by tonka3000** [comment]
Thanks for the info. I will try to get the info from the cmake tools extension.

**Comment by tonka3000** [comment]
Hey @zrno ,

I've impl. the `${buildType}` and `${buildKit}` support into the extension. I can not support the other variables like `${generator}` because the cmake tools extension has no way to get there information from another extension.

Hopefully the cmake tools extension will get an offical API, but they said that it is not on their plan for now, see https://github.com/microsoft/vscode-cmake-tools/issues/1364 and https://github.com/microsoft/vscode-cmake-tools/issues/494

Greetings<br>
Tonka
