### ISSUE TITLE
cannot scan for QT

### ISSUE THREAD

**Issue by thiennc1107** [tonka3000/vscode-qt-tools#36]
I'm just new to both QT and this extension and my tool just cannot scan for qt, can anyone help me with this ?

**Comment by tonka3000** [comment]
Hey,

Please add more details.

- Which OS do you use?
- Which Qt version do you have?
- How do you installed Qt?
- Which compiler?
- Which cmake version do you use?

Greetings

Tonka

**Comment by markio00** [comment]
Hi, I have the same problem and it probably is because i'm not rocking CMake for this project and I'm doing qmake instead.
I noticed a `"qttools.extraSearchDirectories"` in the settings and I tried setting it up and with the log level set to "debug" but it shows me `Command 'Qt: Scan for Qt Kit' resulted in an error 2qttools.scanqtkit' not found)` over and over via popup error.
Then I tried launching a dummy Cmake project jut in case and a button saying "no kit found" or something similiar shown up at the bottom
Now a QT output shown up and the debug told me he was searching in ./build and even into the directories I provided but still nothing found.
In the attempt of clean the output I deleted the cmake infrastructure, rebooted vscode and it suddenly stopped working throwing at me the same popup error as above.

At this point I asume I need CMake to run it anyways but I do not understand how to configure it,
Could u help me out?

VSCode Version: 1.52.1
OS Version: WSL2 Ubuntu 20.04.1 LTS (focal) over Windows_NT x64 10.0.19041
Compiler version: `g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`
Qt has been installed via `apt install qt5-default`
#`qmake --version` output:
```
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
```
#`qmake --version` output:
```
cmake version 3.19.0-rc1
```

**Comment by tonka3000** [comment]
Hey @markio00 ,

You are totally right, you need cmake for the extension. I don't support other build systems right now but I thinking  about adding support for non cmake projects, see more details about it in the issue #38

Right now you need to configure cmake like `cmake -H. -Bbuild ...` (I assume that you working directory is the root folder of your project where the CMakeLists.txt file should exist) before the extension could find Qt. You need also a `find_package(Qt ...` anywhere in your CMakeLists.txt file, so that the path to Qt will get stored in the cmake cache file (in the `build` directory). You can also use the CMake Tools extension from Microsoft to configure the CMake project is you don't like the command line.

So right now you have following options
- write a minimal CMakeLists.txt file with just the `find_package(Qt...)` in it. Just checkout any cmake Qt tutorial on the web
- convert your qmake project files to cmake files
  But this would be a huge change for just using the extension. But since Qt itself switched to cmake with Qt 6, there should be maybe some converters from them (or at least a tutorial)

Greetings

Michael

**Comment by tonka3000** [comment]
@thiennc1107 @markio00 I've close this for now. If you have troubles reopen the issue or file a new one.
